---
- hosts: localhost
  become: true
  connection: local
 
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name: 
          - vim
          - git      
          - powerline-fonts
          - curl
          - httpd
          - ubuntu-restricted-extras
        state: latest
        update_cache: true
       
    - name: UFW - Allow SSH connections
      community.general.ufw
        rule: allow
        name: OpenSSH
